# Site settings
title: retro
author: 简律纯
email: HsiangNianian@outlook.com
description: AI/ML, thoughts? 
logo: 119327113.png

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://retrofor.space/" # the base hostname & protocol for your site

social_links:
  twitter: HsiangNianian
  github: HsiangNianian
  facebook: hsiang.nianian
  soundcloud: hsiang_nianian
  instagram: hsiang_nianian 

google_analytics: G-WQVB7M8ZZ2

disqus:
  shortname: cypress-github-io

show_excerpts: true

feed:
  excerpt_only: true

header_pages:
  - publications.md
  - blog.md
  - Links.md
  
# Build settings
markdown: kramdown
theme: minima
# remote_theme: luoyan35714/LessOrMore
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-remote-theme
