[project]
name = "iamai-adapter-gensokyo"
version = "0.1.6"
description = "Gensokyo adapter for iamai."
authors = [{ name = "简律纯", email = "i@jyunko.cn" }]
license = { text = "MIT" }
readme = "README.md"
keywords = ["bot", "chatbot", "qq", "ontbot", "gensokyo"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Framework :: AsyncIO",
    "Framework :: Robot Framework",
    "Framework :: Robot Framework :: Library",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Topic :: Communications :: Chat",
]
requires-python = ">=3.9"
dependencies = ["iamai>=0.0.4"]

[project.urls]
Homepage = "https://iamai.is-a.dev/"
Documentation = "https://iamai.is-a.dev/"
Repository = "https://github.com/retrofor/iamai"
Changelog = "https://iamai.is-a.dev/changelog.html"

[tool.hatch.build]
exclude = ["iamai/__init__.py", "iamai/adapter/__init__.py"]
include = ["iamai/adapter/gensokyo"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"