backend:
  name: github
  repo: retrofor/iamai # Path to your GitHub repository
  # optional, defaults to master
  branch: main
  use_graphql: true
  squash_merges: true
  commit_messages:
    create: âœ¨{{author-login}} Create {{collection}} â€œ{{slug}}â€
    update: ğŸ±â€ğŸ{{author-login}} Update {{collection}} â€œ{{slug}}â€
    delete: ğŸ±â€ğŸ‘¤{{author-login}} Delete {{collection}} â€œ{{slug}}â€
    uploadMedia: âœ¨{{author-login}} Upload â€œ{{path}}â€
    deleteMedia: ğŸ±â€{{author-login}} Delete â€œ{{path}}â€
    openAuthoring: '{{author-login}}: {{message}}'
publish_mode: editorial_workflow
media_folder: "/website/static/img/post" # å­˜æ”¾å›¾ç‰‡çš„æ–‡ä»¶å¤¹
public_folder: "/website/img/post" # ä¸Šä¼ å›¾ç‰‡çš„srcå±æ€§ä¼šä»¥è¯¥è·¯å¾„å¼€å¤´
logo_url: https://iamai.retrofor.space/img/retro.ico

# i18n:
#   # Required and can be one of multiple_folders, multiple_files or single_file
#   # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
#   # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
#   # single_file - persists a single file in `<folder>/<slug>.<extension>`
#   structure: multiple_folders

#   # Required - a list of locales to show in the editor UI
#   locales: [en, zh]

#   # Optional, defaults to the first item in locales.
#   # The locale to be used for fields validation and as a baseline for the entry.
#   default_locale: en

collections:
  - name: "opt" # å®šä¹‰è¯¥collectionçš„è·¯å¾„
    label: "blog" # åå°æ˜¾ç¤ºçš„åå­—
    folder: "blog"
    create: true # å…è®¸åˆ›å»ºæ–°æ–‡ä»¶
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    slug: "{{slug}}" # æ–‡ä»¶åå­—æ¨¡ç‰ˆï¼Œ{{slug}} å–è‡ªtitle
    fields: # å®šä¹‰front matterçš„æ˜¾ç¤ºä¸æ•°æ®ç±»å‹
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Authors",
          name: "authors",
          widget: "string",
          default: "Hsiang_Nianian",
        }
      - { label: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Series", name: "series", widget: "list", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Lastmod",
          name: "lastmod",
          widget: "date",
          default: "",
          required: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Alt",
          name: "featuredalt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Path",
          name: "featuredpath",
          widget: "string",
          default: "img/post",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Show TOC",
          name: "showtoc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Post Content", name: "body", widget: "markdown" }
  - name: "opt-2" # å®šä¹‰è¯¥collectionçš„è·¯å¾„
    label: "docs" # åå°æ˜¾ç¤ºçš„åå­—
    folder: "docs"
    create: true # å…è®¸åˆ›å»ºæ–°æ–‡ä»¶
    nested:
      depth: 100 # max depth to show in the collection tree
      summary: '{{title}}' # optional summary for a tree node, defaults to the inferred title field
    slug: "{{slug}}" # æ–‡ä»¶åå­—æ¨¡ç‰ˆï¼Œ{{slug}} å–è‡ªtitle
    fields: # å®šä¹‰front matterçš„æ˜¾ç¤ºä¸æ•°æ®ç±»å‹
      - { label: "Title", name: "title", widget: "string" }
      - {
          label: "Authors",
          name: "authors",
          widget: "string",
          default: "Hsiang_Nianian",
        }
      - { label: "Type", name: "type", widget: "string", default: "post" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Tags", name: "tags", widget: "list" }
      - { label: "Series", name: "series", widget: "list", required: false }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - {
          label: "Lastmod",
          name: "lastmod",
          widget: "date",
          default: "",
          required: false,
          format: "YYYY-MM-DD",
        }
      - {
          label: "Description",
          name: "description",
          widget: "text",
          required: false,
        }
      - {
          label: "Featured Image",
          name: "featured",
          widget: "image",
          required: false,
        }
      - {
          label: "Featured Alt",
          name: "featuredalt",
          widget: "string",
          required: false,
        }
      - {
          label: "Featured Path",
          name: "featuredpath",
          widget: "string",
          default: "img/post",
          required: false,
        }
      - { label: "Slug", name: "slug", widget: "string", required: false }
      - {
          label: "Draft",
          name: "draft",
          widget: "boolean",
          default: false,
          required: false,
        }
      - {
          label: "Show TOC",
          name: "showtoc",
          widget: "boolean",
          default: true,
          required: false,
        }
      - { label: "Post Content", name: "body", widget: "markdown" }
