name: Deploy

on:
  push:
    branches:
      - main
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

jobs:
#   deploy:
#     name: Deploy to GitHub Pages
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-node@v3
#         with:
#           node-version: 18
#           cache: yarn
          
#       - name: change dir
#         run: cd website
        
#       - name: Install dependencies
#         run: yarn install # --frozen-lockfile
#       - name: Build website
#         run: |
#             yarn workspace website build
            
#       - name: Deploy to GitHub Pages
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           # Build output to publish to the `gh-pages` branch:
#           publish_dir: ./build
#           # The following lines assign commit authorship to the official
#           # GH-Actions bot for deploys to `gh-pages` branch:
#           # https://github.com/actions/checkout/issues/13#issuecomment-724415212
#           # The GH actions bot is used by default if you didn't specify the two fields.
#           # You can swap them out with your own user credentials.
#           user_name: github-actions[bot]
#           user_email: 41898282+github-actions[bot]@users.noreply.github.com



  publish:
    runs-on: ubuntu-latest
    concurrency:
      group: website-deploy-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v3

#       - name: Setup Python Environment
#         uses: ./.github/actions/setup-python

      - name: Setup Node Environment
        uses: ./.github/actions/setup-node

#       - name: Build API Doc
#         uses: ./.github/actions/build-api-doc

      - name: change dir
        run: |
            cd ./website
            ls 
        
      - name: Build Doc
        run: yarn workspace docs build

      - name: Get Branch Name
        run: echo "BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_ENV

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v2
        with:
          publish-dir: "./website/build"
          production-deploy: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: "Deploy ${{ env.BRANCH_NAME }}@${{ github.sha }}"
          enable-commit-comment: false
          alias: ${{ env.BRANCH_NAME }}
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.SITE_ID }}
